# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 86c394f6132b737254c6c2131a53360b7f91d95a7db75487416e490af7a23ee9c4d489952d7feb7bfa9664b07cd3ebd31e3bd9697307e1da05a82bb3e309a520

test:
  secret_key_base: 6506506f8685f997f90c25cacea9fc164cd61d72a0d064a544df0e90b1c8dea37e07c761abb48e8ad08a66ed8ea3e5bd49abea25019bf22f9c8292227eabb73a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
